version: "3.2"

services:
  # App
  2_faces_net_app:
    container_name: 2_FACES_NET-backend_app
    build: ./app
    restart: always
    env_file: .env
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
      - "${SOCKET_MAIN_PORT}:${SOCKET_MAIN_PORT}"
      - "${SOCKET_CODE_SENDER}-${SOCKET_CODE_SENDER1}:${SOCKET_CODE_SENDER}-${SOCKET_CODE_SENDER1}"
      - "${SOCKET_COLLECTOR}-${SOCKET_COLLECTOR1}:${SOCKET_COLLECTOR}-${SOCKET_COLLECTOR1}"
    expose:
      - "${SERVER_PORT}"
      - "${SOCKET_MAIN_PORT}"
      - "${SOCKET_CODE_SENDER}-${SOCKET_CODE_SENDER1}"
      - "${SOCKET_COLLECTOR}-${SOCKET_COLLECTOR1}"
    depends_on:
      - 2_faces_net_mongo
    links:
      - 2_faces_net_mongo

  # MongoDB
  2_faces_net_mongo:
    container_name: 2_FACES_NET-backend_mongo
    image: mongo:latest
    restart: always
    env_file: .env
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - '.mongo:/docker-entrypoint-initdb.d'

#volumes:
#  mongo:
#    driver: local
